// Complete element data for the periodic table
const periodicTableData = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: "1.008",
    category: "nonmetal",
    group: 1,
    period: 1,
    block: "s",
    electronConfig: "1s¹",
    description: "Hydrogen is the lightest element and most abundant chemical substance in the universe, constituting roughly 75% of all normal matter."
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    mass: "4.0026",
    category: "noble-gas",
    group: 18,
    period: 1,
    block: "s",
    electronConfig: "1s²",
    description: "Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table."
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    mass: "6.94",
    category: "alkali-metal",
    group: 1,
    period: 2,
    block: "s",
    electronConfig: "1s² 2s¹",
    description: "Lithium is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element."
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: "9.0122",
    category: "alkaline-earth",
    group: 2,
    period: 2,
    block: "s",
    electronConfig: "1s² 2s²",
    description: "Beryllium is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements."
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    mass: "10.81",
    category: "metalloid",
    group: 13,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p¹",
    description: "Boron is a chemical element with properties between those of carbon and aluminum. It is a semiconductor rather than a metallic element."
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    mass: "12.011",
    category: "nonmetal",
    group: 14,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p²",
    description: "Carbon is a nonmetallic chemical element that is the basis of organic compounds and is essential to all known life on Earth."
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: "14.007",
    category: "nonmetal",
    group: 15,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p³",
    description: "Nitrogen is a colorless, odorless, tasteless gas that makes up about 78% of Earth's atmosphere and is a constituent of all living tissues."
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    mass: "15.999",
    category: "nonmetal",
    group: 16,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p⁴",
    description: "Oxygen is a highly reactive nonmetal and oxidizing agent that readily forms oxides with most elements as well as with other compounds."
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    mass: "18.998",
    category: "halogen",
    group: 17,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p⁵",
    description: "Fluorine is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. It is the most electronegative element."
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    mass: "20.180",
    category: "noble-gas",
    group: 18,
    period: 2,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶",
    description: "Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air."
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    mass: "22.990",
    category: "alkali-metal",
    group: 1,
    period: 3,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s¹",
    description: "Sodium is a soft, silvery-white, highly reactive metal. It is an alkali metal and is in group 1 of the periodic table."
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: "24.305",
    category: "alkaline-earth",
    group: 2,
    period: 3,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s²",
    description: "Magnesium is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table."
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminum",
    mass: "26.982",
    category: "post-transition-metal",
    group: 13,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p¹",
    description: "Aluminum is a silvery-white, soft, nonmagnetic, ductile metal. It is the third most abundant element in the Earth's crust."
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    mass: "28.085",
    category: "metalloid",
    group: 14,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p²",
    description: "Silicon is a hard and brittle crystalline solid with a blue-grey metallic lustre. It is a tetravalent metalloid and semiconductor."
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: "30.974",
    category: "nonmetal",
    group: 15,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p³",
    description: "Phosphorus is a multivalent nonmetal of the nitrogen group. It exists in several forms, the most common of which is white phosphorus."
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    mass: "32.06",
    category: "nonmetal",
    group: 16,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁴",
    description: "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic."
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: "35.45",
    category: "halogen",
    group: 17,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁵",
    description: "Chlorine is a yellow-green gas at room temperature. It is an extremely reactive element and a strong oxidizing agent."
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    mass: "39.948",
    category: "noble-gas",
    group: 18,
    period: 3,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶",
    description: "Argon is the third-most abundant gas in the Earth's atmosphere. It is a noble gas and is chemically inert."
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    mass: "39.098",
    category: "alkali-metal",
    group: 1,
    period: 4,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
    description: "Potassium is a silvery-white metal that is soft enough to be cut with a knife. It is one of the most reactive elements in the periodic table."
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: "40.078",
    category: "alkaline-earth",
    group: 2,
    period: 4,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
    description: "Calcium is a reactive, soft metal that is a member of the alkaline earth elements. It is the fifth most abundant element in Earth's crust."
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: "44.956",
    category: "transition-metal",
    group: 3,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹",
    description: "Scandium is a silvery-white metallic d-block element. It has historically been classified as a rare earth element."
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: "47.867",
    category: "transition-metal",
    group: 4,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d²",
    description: "Titanium is a lustrous transition metal with a silver color, low density, and high strength. It is resistant to corrosion in sea water, aqua regia, and chlorine."
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    mass: "50.942",
    category: "transition-metal",
    group: 5,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d³",
    description: "Vanadium is a hard, silvery-grey, ductile, and malleable transition metal. It is primarily used in the production of steel alloys."
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: "51.996",
    category: "transition-metal",
    group: 6,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d⁵",
    description: "Chromium is a steely-grey, lustrous, hard and brittle transition metal. It is the main additive in stainless steel."
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: "54.938",
    category: "transition-metal",
    group: 7,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁵",
    description: "Manganese is a chemical element with symbol Mn and atomic number 25. It is a hard, brittle, silvery metal, often found in minerals in combination with iron."
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    mass: "55.845",
    category: "transition-metal",
    group: 8,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶",
    description: "Iron is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core."
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: "58.933",
    category: "transition-metal",
    group: 9,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁷",
    description: "Cobalt is a chemical element with symbol Co and atomic number 27. It is a hard, lustrous, silver-gray metal."
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: "58.693",
    category: "transition-metal",
    group: 10,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁸",
    description: "Nickel is a silvery-white lustrous metal with a slight golden tinge. It is one of four elements that are ferromagnetic at room temperature."
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    mass: "63.546",
    category: "transition-metal",
    group: 11,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d¹⁰",
    description: "Copper is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. It is used as a conductor of heat and electricity."
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    mass: "65.38",
    category: "transition-metal",
    group: 12,
    period: 4,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰",
    description: "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table."
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: "69.723",
    category: "post-transition-metal",
    group: 13,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p¹",
    description: "Gallium is a chemical element with symbol Ga and atomic number 31. It is a soft, silvery metal that melts at room temperature."
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: "72.630",
    category: "metalloid",
    group: 14,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p²",
    description: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group."
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    mass: "74.922",
    category: "metalloid",
    group: 15,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p³",
    description: "Arsenic is a chemical element with symbol As and atomic number 33. It occurs in many minerals, usually in combination with sulfur and metals."
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    mass: "78.971",
    category: "nonmetal",
    group: 16,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁴",
    description: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table."
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    mass: "79.904",
    category: "halogen",
    group: 17,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁵",
    description: "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature."
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    mass: "83.798",
    category: "noble-gas",
    group: 18,
    period: 4,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶",
    description: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements."
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    mass: "85.468",
    category: "alkali-metal",
    group: 1,
    period: 5,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹",
    description: "Rubidium is a chemical element with symbol Rb and atomic number 37. It is a soft, silvery-white metallic element of the alkali metal group."
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: "87.62",
    category: "alkaline-earth",
    group: 2,
    period: 5,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s²",
    description: "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, it is a soft silver-white yellowish metallic element."
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: "88.906",
    category: "transition-metal",
    group: 3,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹",
    description: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides."
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: "91.224",
    category: "transition-metal",
    group: 4,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d²",
    description: "Zirconium is a chemical element with symbol Zr and atomic number 40. It is a lustrous, grey-white, strong transition metal that resembles hafnium."
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: "92.906",
    category: "transition-metal",
    group: 5,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁴",
    description: "Niobium is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, ductile transition metal, often found in the minerals pyrochlore and columbite."
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: "95.95",
    category: "transition-metal",
    group: 6,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁵",
    description: "Molybdenum is a chemical element with symbol Mo and atomic number 42. It is a silvery metal with a gray cast, and has the sixth-highest melting point of any element."
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: "[98]",
    category: "transition-metal",
    group: 7,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d⁵",
    description: "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive."
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: "101.07",
    category: "transition-metal",
    group: 8,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁷",
    description: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table."
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: "102.91",
    category: "transition-metal",
    group: 9,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d⁸",
    description: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal."
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: "106.42",
    category: "transition-metal",
    group: 10,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 4d¹⁰",
    description: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston."
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    mass: "107.87",
    category: "transition-metal",
    group: 11,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d¹⁰",
    description: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal."
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: "112.41",
    category: "transition-metal",
    group: 12,
    period: 5,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰",
    description: "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury."
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    mass: "114.82",
    category: "post-transition-metal",
    group: 13,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p¹",
    description: "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that makes up 0.21 parts per million of the Earth's crust."
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    mass: "118.71",
    category: "post-transition-metal",
    group: 14,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p²",
    description: "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in group 14 of the periodic table."
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: "121.76",
    category: "metalloid",
    group: 15,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p³",
    description: "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite."
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: "127.60",
    category: "metalloid",
    group: 16,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁴",
    description: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid."
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    mass: "126.90",
    category: "halogen",
    group: 17,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁵",
    description: "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a lustrous, purple-black non-metallic solid at standard conditions."
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    mass: "131.29",
    category: "noble-gas",
    group: 18,
    period: 5,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶",
    description: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts."
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    mass: "132.91",
    category: "alkali-metal",
    group: 1,
    period: 6,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹",
    description: "Cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C."
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    mass: "137.33",
    category: "alkaline-earth",
    group: 2,
    period: 6,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s²",
    description: "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal."
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: "138.91",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 5d¹",
    description: "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air."
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: "140.12",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹ 5d¹",
    description: "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, ductile metal which easily oxidizes in air."
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: "140.91",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f³",
    description: "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is a soft, silvery, malleable and ductile metal, valued for its magnetic, electrical, chemical, and optical properties."
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: "144.24",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁴",
    description: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air."
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: "[145]",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁵",
    description: "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500–600 grams naturally occurring in Earth's crust at any given time."
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: "150.36",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁶",
    description: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air."
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    mass: "151.96",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁷",
    description: "Europium is a chemical element with symbol Eu and atomic number 63. It is a moderately hard, silvery metal which readily oxidizes in air and water."
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: "157.25",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁷ 5d¹",
    description: "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal."
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: "158.93",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f⁹",
    description: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife."
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: "162.50",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁰",
    description: "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster."
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: "164.93",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹¹",
    description: "Holmium is a chemical element with symbol Ho and atomic number 67. It is a relatively soft and malleable silvery-white metal."
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    mass: "167.26",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹²",
    description: "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements."
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: "168.93",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹³",
    description: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series."
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: "173.05",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴",
    description: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series."
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: "174.97",
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹",
    description: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air."
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: "178.49",
    category: "transition-metal",
    group: 4,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d²",
    description: "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals."
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: "180.95",
    category: "transition-metal",
    group: 5,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d³",
    description: "Tantalum is a chemical element with symbol Ta and atomic number 73. It is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant."
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    mass: "183.84",
    category: "transition-metal",
    group: 6,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁴",
    description: "Tungsten, or wolfram, is a chemical element with symbol W and atomic number 74. The free element is remarkable for its robustness, especially the fact that it has the highest melting point of all the elements."
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: "186.21",
    category: "transition-metal",
    group: 7,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁵",
    description: "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table."
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    mass: "190.23",
    category: "transition-metal",
    group: 8,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁶",
    description: "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores."
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: "192.22",
    category: "transition-metal",
    group: 9,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d⁷",
    description: "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is the second-densest element (after osmium)."
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: "195.08",
    category: "transition-metal",
    group: 10,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹ 4f¹⁴ 5d⁹",
    description: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal."
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    mass: "196.97",
    category: "transition-metal",
    group: 11,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹ 4f¹⁴ 5d¹⁰",
    description: "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal."
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: "200.59",
    category: "transition-metal",
    group: 12,
    period: 6,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰",
    description: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum."
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: "204.38",
    category: "post-transition-metal",
    group: 13,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p¹",
    description: "Thallium is a chemical element with symbol Tl and atomic number 81. It is a gray post-transition metal that is not found free in nature."
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    mass: "207.2",
    category: "post-transition-metal",
    group: 14,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p²",
    description: "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials."
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: "208.98",
    category: "post-transition-metal",
    group: 15,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p³",
    description: "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony."
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    mass: "[209]",
    category: "post-transition-metal",
    group: 16,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁴",
    description: "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium."
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    mass: "[210]",
    category: "halogen",
    group: 17,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁵",
    description: "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements."
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    mass: "[222]",
    category: "noble-gas",
    group: 18,
    period: 6,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶",
    description: "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas."
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    mass: "[223]",
    category: "alkali-metal",
    group: 1,
    period: 7,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s¹",
    description: "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive; its most stable isotope, francium-223, has a half-life of only 22 minutes."
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    mass: "[226]",
    category: "alkaline-earth",
    group: 2,
    period: 7,
    block: "s",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s²",
    description: "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals."
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: "[227]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 6d¹",
    description: "Actinium is a chemical element with symbol Ac and atomic number 89. It is a radioactive, silvery-white metallic element."
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    mass: "232.04",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 6d²",
    description: "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only four radioactive elements that still occur naturally in large quantities as a primordial element."
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: "231.04",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f² 6d¹",
    description: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids."
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    mass: "238.03",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f³ 6d¹",
    description: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table."
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    mass: "[237]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁴ 6d¹",
    description: "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element."
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    mass: "[244]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁶",
    description: "Plutonium is a radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air."
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    mass: "[243]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁷",
    description: "Americium is a chemical element with symbol Am and atomic number 95. It is a transuranic member of the actinide series, in the periodic table."
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    mass: "[247]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁷ 6d¹",
    description: "Curium is a chemical element with symbol Cm and atomic number 96. It is a hard, dense, silvery metal with a relatively high melting point and boiling point for an actinide."
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    mass: "[247]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f⁹",
    description: "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series."
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    mass: "[251]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁰",
    description: "Californium is a radioactive chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory."
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: "[252]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹¹",
    description: "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide."
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    mass: "[257]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹²",
    description: "Fermium is a synthetic element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements."
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: "[258]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹³",
    description: "Mendelevium is a synthetic element with symbol Md and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities."
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    mass: "[259]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴",
    description: "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science."
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: "[266]",
    category: "actinide",
    group: 3,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 7p¹",
    description: "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements."
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: "[267]",
    category: "transition-metal",
    group: 4,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d²",
    description: "Rutherfordium is a synthetic chemical element with symbol Rf and atomic number 104. It is named in honor of physicist Ernest Rutherford."
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    mass: "[268]",
    category: "transition-metal",
    group: 5,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d³",
    description: "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia, where it was first produced."
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: "[269]",
    category: "transition-metal",
    group: 6,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁴",
    description: "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named in honor of American nuclear chemist Glenn T. Seaborg."
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    mass: "[270]",
    category: "transition-metal",
    group: 7,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁵",
    description: "Bohrium is a synthetic chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr."
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    mass: "[269]",
    category: "transition-metal",
    group: 8,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁶",
    description: "Hassium is a synthetic chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse."
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    mass: "[278]",
    category: "unknown",
    group: 9,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁷",
    description: "Meitnerium is a synthetic chemical element with symbol Mt and atomic number 109. It is named after Lise Meitner, the Austrian-Swedish physicist and mathematician who was one of the discoverers of nuclear fission."
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: "[281]",
    category: "unknown",
    group: 10,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁸",
    description: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is named after Darmstadt, Germany, where it was first produced."
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: "[282]",
    category: "unknown",
    group: 11,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d⁹",
    description: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is named after the German physicist Wilhelm Conrad Röntgen, who discovered X-rays."
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: "[285]",
    category: "transition-metal",
    group: 12,
    period: 7,
    block: "d",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰",
    description: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is named after the astronomer Nicolaus Copernicus."
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    mass: "[286]",
    category: "unknown",
    group: 13,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p¹",
    description: "Nihonium is a chemical element with symbol Nh and atomic number 113. It is named after Japan (Nihon in Japanese)."
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    mass: "[289]",
    category: "unknown",
    group: 14,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p²",
    description: "Flerovium is a chemical element with symbol Fl and atomic number 114. It is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia."
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    mass: "[290]",
    category: "unknown",
    group: 15,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p³",
    description: "Moscovium is a chemical element with symbol Mc and atomic number 115. It is named after the Moscow Oblast of Russia."
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: "[293]",
    category: "unknown",
    group: 16,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p⁴",
    description: "Livermorium is a chemical element with symbol Lv and atomic number 116. It is named after the Lawrence Livermore National Laboratory in the United States."
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: "[294]",
    category: "unknown",
    group: 17,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p⁵",
    description: "Tennessine is a chemical element with symbol Ts and atomic number 117. It is named after the U.S. state of Tennessee."
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    mass: "[294]",
    category: "unknown",
    group: 18,
    period: 7,
    block: "p",
    electronConfig: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f¹⁴ 6d¹⁰ 7p⁶",
    description: "Oganesson is a chemical element with symbol Og and atomic number 118. It is named after the Russian nuclear physicist Yuri Oganessian."
  }
];
